# Generated by Django 3.1 on 2020-08-31 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('text', models.CharField(max_length=5000, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.FileField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
