# Generated by Django 3.1 on 2020-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200902_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='brieftext',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
