# Generated by Django 3.1 on 2020-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200902_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
