# Generated by Django 3.1 on 2020-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201005_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='brieftext',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
