# Generated by Django 3.1 on 2020-08-31 17:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(blank=True, default='Blank', max_length=200, null=True)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('name_fa', models.CharField(max_length=100, null=True, validators=[user.models.CustomUser.validate_namefa])),
                ('lastname_fa', models.CharField(max_length=100, null=True, validators=[user.models.CustomUser.validate_namefa])),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('workplace_name', models.CharField(max_length=100, null=True)),
                ('workplace_num', models.CharField(max_length=100, null=True, validators=[user.models.CustomUser.validate_phonenum])),
                ('codemli', models.CharField(max_length=100, null=True, unique=True, validators=[user.models.CustomUser.validate_codemli])),
                ('phonenum', models.CharField(max_length=100, null=True, validators=[user.models.CustomUser.validate_phonenum])),
                ('postalcode', models.CharField(blank=True, max_length=100, null=True, validators=[user.models.CustomUser.validate_postalcode])),
                ('fday', models.BooleanField(default=False, null=True)),
                ('sday', models.BooleanField(default=False, null=True)),
                ('student_id', models.CharField(blank=True, default='Not a student', max_length=20, null=True)),
                ('activate', models.BooleanField(default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
