# Generated by Django 3.1 on 2020-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201020_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='totalscore',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
