# Generated by Django 3.1 on 2020-10-31 21:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201024_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codemli',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[user.models.CustomUser.validate_codemli]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='workplace_num',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[user.models.CustomUser.validate_phonenum]),
        ),
    ]
